[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "YOUR_PROJECT_NAME"
authors = [{name = "Willem van Heemstra", email = "wvanheemstra@icloud.com"}]
dynamic = ["version", "description"]
